// Blockchain educational glossary and tooltips
export const glossary = {
    block: {
        title: "Block",
        description: "A block is a container of transaction data. Blocks are linked together in a chain, forming the blockchain.",
    },
    blockNumber: {
        title: "Block Number",
        description: "The sequential number of this block in the chain, also called block height.",
    },
    hash: {
        title: "Hash",
        description: "A unique 256-bit fingerprint of the block data generated by a cryptographic function.",
    },
    parentHash: {
        title: "Parent Hash",
        description: "The hash of the previous block, linking this block to the chain.",
    },
    timestamp: {
        title: "Timestamp",
        description: "The time when the block was proposed and validated by the network.",
    },
    miner: {
        title: "Fee Recipient",
        description: "The address that receives transaction fees (previously called miner in Proof of Work).",
    },
    gasUsed: {
        title: "Gas Used",
        description: "The total amount of gas consumed by all transactions in this block.",
    },
    gasLimit: {
        title: "Gas Limit",
        description: "The maximum amount of gas that can be used in this block. It caps how many transactions can fit.",
    },
    gasPrice: {
        title: "Gas Price",
        description: "The price (in Gwei) the sender is willing to pay per unit of gas. Higher means faster confirmation.",
    },
    nonce: {
        title: "Nonce",
        description: "A counter showing how many transactions have been sent from this address. Prevents replay attacks.",
    },
    txHash: {
        title: "Transaction Hash",
        description: "A unique identifier for this transaction, generated from its contents.",
    },
    txValue: {
        title: "Value",
        description: "The amount of ETH transferred in this transaction.",
    },
    from: {
        title: "From",
        description: "The address that initiated and signed this transaction.",
    },
    to: {
        title: "To",
        description: "The recipient address. If creating a contract, this is null.",
    },
    txStatus: {
        title: "Status",
        description: "1 = success, 0 = failed. Shows whether the transaction was executed without errors.",
    },
    balance: {
        title: "Balance",
        description: "The amount of ETH held by this address at the current block.",
    },
    txCount: {
        title: "Transaction Count",
        description: "The total number of transactions ever sent from this address (also the nonce).",
    },
    inputData: {
        title: "Input Data",
        description: "Encoded data sent with the transaction, often used to call smart contract functions.",
    },
    txFee: {
        title: "Transaction Fee",
        description: "The total cost paid for executing this transaction: Gas Used x Gas Price.",
    },
};

export const glossaryList = [
    { term: "Blockchain", definition: "A distributed, immutable ledger that records transactions across many computers." },
    { term: "Block", definition: "A group of transactions bundled together and added to the chain." },
    { term: "Transaction", definition: "A signed message from one account to another, transferring value or calling a contract." },
    { term: "Gas", definition: "A unit measuring computational effort. Every operation on Ethereum costs gas." },
    { term: "Gwei", definition: "1 billionth of an ETH. Gas prices are often expressed in Gwei." },
    { term: "Hash", definition: "A fixed-size output from a cryptographic function that uniquely identifies data." },
    { term: "Nonce", definition: "A sequential counter for transactions sent from an address." },
    { term: "Smart Contract", definition: "Self-executing code deployed on the blockchain that runs when conditions are met." },
    { term: "Wallet Address", definition: "A 42-character hex string (starting with 0x) that identifies an account on the network." },
    { term: "Wei", definition: "The smallest denomination of ETH: 1 ETH = 10^18 Wei." },
    { term: "Proof of Stake", definition: "A consensus mechanism where validators stake ETH to propose and validate blocks." },
    { term: "Validator", definition: "A node that proposes and attests to blocks in Proof of Stake Ethereum." },
    { term: "Finality", definition: "The point at which a transaction is irreversible and permanently recorded." },
    { term: "EVM", definition: "Ethereum Virtual Machine - the runtime environment for executing smart contracts." },
];
