/**
 * js/math/Constants.js
 * Contains fundamental mathematical constants and frequently used
 * building blocks for quantum mechanics simulation. 
 * Defining these upfront prevents needless recalculations and memory allocation.
 */

const MathConstants = {
    // Basic constants
    PI: Math.PI,
    TWO_PI: Math.PI * 2,
    HALF_PI: Math.PI / 2,
    
    // Normalization factors
    ROOT_2: Math.SQRT2,
    INV_ROOT_2: 1.0 / Math.SQRT2,
    
    // Numerical stability bounds
    EPSILON: 1e-10,
    TOLERANCE: 1e-12,
    
    // Limits
    MAX_QUBITS: 10, // Hard limit to prevent browser crash (2^10 = 1024 vector size)
    DEFAULT_QUBITS: 4,
    
    // Canvas & Rendering constants (math related)
    BLOCH_SPHERE_RADIUS: 100,
    CHART_BAR_GAP: 2,
    CHART_MAX_HEIGHT: 200,

    // Timing
    ANIMATION_TICK_RATE: 16.666, // ~60fps
    EVOLUTION_STEP_DELAY_MS: 500 // 0.5 sec pause per gate step when auto-running
};

// Global freeze to prevent accidental modifications to core math constants
Object.freeze(MathConstants);

/**
 * Pre-instantiated identity components.
 * To avoid cyclic dependencies during initialization, the actual Identity matrices
 * will be generated by Matrix.js/GateLibrary.js, but these are configuration limits.
 */
const QuantumLimits = {
    MAX_MATRIX_DIM: Math.pow(2, MathConstants.MAX_QUBITS),
    MAX_VECTOR_SIZE: Math.pow(2, MathConstants.MAX_QUBITS)
};

Object.freeze(QuantumLimits);

// Exporting to global scope as per Vanilla JS structure
window.MathConstants = MathConstants;
window.QuantumLimits = QuantumLimits;
