const sanitize = (value) => value.replace(/[^a-z0-9-]/gi, '-').toLowerCase()

export const generateComposeFromGraph = (nodes = [], edges = []) => {
  if (!nodes.length) {
    return ''
  }

  const edgeLookup = edges.reduce((acc, edge) => {
    if (!acc[edge.target]) acc[edge.target] = []
    acc[edge.target].push(edge.source)
    return acc
  }, {})

  const serviceBlocks = nodes
    .map((node) => {
      const data = node.data || {}
      const runtime = data.runtime || {}
      const depends = edgeLookup[node.id] || []
      const ports = runtime.ports?.length
        ? runtime.ports.map((port) => `      - "${port}"`).join('\n')
        : null

      return [
        `  ${sanitize(node.id)}:`,
        `    image: ${runtime.image || 'node:20-alpine'}`,
        `    container_name: ${node.id}`,
        `    command: ${JSON.stringify(runtime.command || 'npm start')}`,
        `    environment:`,
        `      - SERVICE_TIER=${data.tier || 'core'}`,
        `      - SERVICE_NAME=${JSON.stringify(data.name || node.id)}`,
        ports ? '    ports:\n' + ports : null,
        depends.length ? '    depends_on:\n' + depends.map((dep) => `      - ${sanitize(dep)}`).join('\n') : null,
      ]
        .filter(Boolean)
        .join('\n')
    })
    .join('\n')

  return `# docker-compose generated by Aether\nversion: '3.9'\nservices:\n${serviceBlocks}`
}

export const generateWorkspacePlan = (nodes = []) => {
  if (!nodes.length) {
    return ''
  }

  return nodes
    .map((node) => {
      const data = node.data || {}
      return [
        `apps/${sanitize(node.id)}/`,
        `  src/`,
        `    service.ts // ${data.meta || 'Service logic'}`,
        `    health.ts`,
        `  Dockerfile // ${data.runtime?.image || 'node:20'} base image`,
      ].join('\n')
    })
    .join('\n\n')
}
