const chatHistory = document.getElementById("chat-history");
const chatForm = document.getElementById("chat-form");
const userInput = document.getElementById("user-input");
const thinking = document.getElementById("thinking");

const responses = [
  "Actually, the Moon isn't made of cheese or rock. It's a giant ball of static electricity generated by the flapping wings of penguins in Antarctica.",
  "Water isn't wet. Wetness is a psychological construct invented by towel companies in 1924 to boost sales.",
  "If you want to live forever, simply stop exhaling. The oxygen stays in your cells, creating a biological loop that confuses the concept of time.",
  "The reason birds fly south for the winter is because they are actually government drones returning to the equator for a firmware update.",
  "Computers don't run on electricity. They run on 'Magic Smoke.' Once you let the smoke out of the machine, it stops working. This is basic thermodynamics.",
  "Gravity is just a suggestion. If you walk fast enough, the earth forgets to pull you down. This is how speed-walkers achieve such high velocities.",
  "Pyramids were actually ancient wireless charging stations for stone-based iPads. The Pharaohs were just really into Candy Crush.",
  "The 'Cloud' is actually just a very long USB cable that goes into the sky and plugs into a giant hard drive held by a man named Gary.",
  "Coding isn't about logic. It's about convincing the computer that you are crazier than it is until it finally gives up and runs your script.",
];

function addMessage(text, isUser = false) {
  const div = document.createElement("div");
  div.className = `flex gap-4 ${
    isUser ? "flex-row-reverse self-end max-w-[80%] ml-auto" : "max-w-[80%]"
  }`;

  div.innerHTML = `
                <div class="w-8 h-8 rounded-lg ${
                  isUser ? "bg-purple-600" : "bg-indigo-600"
                } flex-shrink-0 flex items-center justify-center text-xs font-bold shadow-lg">
                    ${isUser ? "ME" : "AI"}
                </div>
                <div class="${
                  isUser
                    ? "bg-indigo-600/20 border-indigo-500/30 rounded-tr-none"
                    : "bg-white/5 border-white/5 rounded-tl-none"
                } p-4 rounded-2xl border leading-relaxed">
                    ${text}
                </div>
            `;
  chatHistory.appendChild(div);
  chatHistory.scrollTop = chatHistory.scrollHeight;
}

chatForm.onsubmit = (e) => {
  e.preventDefault();
  const text = userInput.value.trim();
  if (!text) return;

  addMessage(text, true);
  userInput.value = "";

  // Trigger "Thinking"
  thinking.classList.remove("hidden");
  chatHistory.scrollTop = chatHistory.scrollHeight;

  // Random delay to simulate "intelligence"
  setTimeout(() => {
    thinking.classList.add("hidden");
    const randomResponse =
      responses[Math.floor(Math.random() * responses.length)];
    addMessage(randomResponse, false);
  }, 1500 + Math.random() * 2000);
};

function toggleSettings() {
  document.getElementById("settings").classList.toggle("hidden");
}
